# site settings
title: Inceptions AI
subtitle:
email: hello@inceptions.ai
description: Fun and Sentient Artificial Intelligence aligned with HUMAN
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site


# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:


# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
