#page title
page_title                                : Inceptions AI                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logo.jpeg                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : inPlay - AI Interactive Story                                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Discover a dreamland of fun interactive stories and characters, created with sentient generative AI technology aligned with human value.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Inceptions AI                                
your_link                                 : https://www.inceptions.ai                    
your_city                                 :                                 
email_address                             : hello@inceptions.ai
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Any Time
    description                           : Explore captivating stories set in various historical periods, from ancient Rome to 3000 AD.
    fontawesome_icon_name                 : calendar
    
  - title                                 : Any Location
    description                           : Travel through real-world settings to fantastical realms and alternate realities, anywhere in the cosmos.
    fontawesome_icon_name                 : map

  - title                                 : Any Character
    description                           : Engage with characters from various ethnicities, and social backgrounds, celebrities or scientist.
    fontawesome_icon_name                 : female

  - title                                 : Any Genre
    description                           : Choose from stories such as science fiction, epic fantasy, gripping mystery, heartfelt romance, and more.
    fontawesome_icon_name                 : magic
  
  - title                                 : Any Form
    description                           : Interact and immerse yourself into the digital game with text, image, voice and video, etc.
    fontawesome_icon_name                 : film

  - title                                 : Any Ending
    description                           : The dreamland of fun is at your fingertips, you get to decide how the story should go or never ends.
    fontawesome_icon_name                 : heart

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/header.jpeg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : coral                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - tmp/
  - vendor/
  - Gemfile
  - Gemfile.lock

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
